language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"

install:
  - pip install $DJANGO
  - python setup.py install

script:
  - "DJANGO_SETTINGS_MODULE=test_project.settings python test_project/manage.py test test_app"
  - "if [ $DJANGO != 'django>=1.4,<1.5' ]; then DJANGO_SETTINGS_MODULE=test_project.custom_user_settings python test_project/manage.py test test_app_custom_user; fi"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="django>=1.7,<1.8"
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
